### ISSUE TITLE
Osa 1.13 Ongelma suden kanssa ...

### ISSUE THREAD

**Issue by opehaapanen** [F1nnn/Punahilkka#1]
DialogActivator.cs koodattu väärin. Tarkista koodi videolta kohdasta 18.45 rivit 73 - 92. Vertaa omaan koodiin.

**Comment by F1nnn** [comment]
muutin koodia mut ei toimi viel

**Comment by opehaapanen** [comment]
DialogActivator.cs on edelleen väärin koodattu. **OnTriggerEnter2D()**-metodissa on väärää koodia jq sulta puuttu **OnTriggerExit2D()** metodi kokonaan. 

<img width="404" alt="image" src="https://github.com/user-attachments/assets/195418d2-b189-486d-959f-4b634a3b5836">

Tarkista **OnTriggerEnter2D()** ja **OnTriggerExit2D()** videolta ja vertaa omaan koodiin:
- Harjoitus 12 - Kohta 15:24, rivit 35 - 41
- Harjoitus 13 - Kohta 18.45 rivi 56 ja rivit 70 - 92.

**Comment by opehaapanen** [comment]
Nyt näyttäs toimivan. Unohdit tehdä OnTriggerExit2D() -metodissa **tag**-tarkistuksrn, mutta se ei aiheuta tässä ongelmia. Boolean muuttuja **canActivate** ei ole tarpeellinen tässä, joten sen voi skipata. Suljen tämän ongelman.
